Capstone Frontend - Add course
BenjaminSemah/capstone-front-end pull request #4
Opened 2022-06-16 19:46 UTC by BenjaminSemah

## What does this PR do?

This PR is raised for the addCourse page

![Capture](https://user-images.githubusercontent.com/88531553/174152135-40c915bb-6781-40d0-91ac-f87810d2b0ed.PNG)

## Description of tasks completed
  - [x] Add page for add course form
  - [x] Implement `addCourse` method using redux toolkit (Thunk)
  - [x] Implement  `add-course` route to addCourse form page
  - [x] Fix all linter errors.  
  
## How should it be tested

Clone the repository
```
git clone https://github.com/BenjaminSemah/capstone-front-end.git
```
Navigate to the folder
```
cd capstone-front-end
```
Checkout the branch
```
git checkout add-course
```
#### Thanks for reviewing my PR 😊

2022-06-16 21:41 UTC, omarsalem7 requested changes
Hi @BenjaminSemah 😊, 

Good job so far! 👏
You have done well reaching this point of the milestone, but there are some issues that you still need to work on to go to the next project but you are almost there! 

![you-are-near](https://media.giphy.com/media/SSR17K6yZWvGCYrfUh/giphy.gif)

## Highlights
- Descriptive pull request ✔️
- No linter errors ✔️
- Add course work in a good way ✔️

## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

2022-06-16 21:41 UTC, omarsalem7 commented on src/components/AddCourseForm.js
> +  };
- [x] It will be better to navigate to home page after add course to could be see the added course.
- It will be done like this by using `useNavigate` hook
Inside `AddCourseForm.js` file 

```js
import { useNavigate } from 'react-router-dom';
export default function AddCourseForm() {
  const dispatch = useDispatch();
  const navigate = useNavigate();
  const [courseData, setCourseData] = useState({
    name: '',
    description: '',
    location: '',
    size: '',
    price: '',
    image: '',
  });

  const handleFormSubmit = (event) => {
    event.preventDefault();
    dispatch(addCourse(courseData));
    navigate('/');
  };
```

2022-06-16 21:41 UTC, omarsalem7 commented on src/pages/addCourse/AddCourse.css
> +}
- [ ] Please remove style from background and add style for your page because this affect in other pages style.
For example, it affect in home page style and it should be the same style as behance design.
![image](https://user-images.githubusercontent.com/53402600/174170415-d3814b3d-caaf-4a85-b162-397c737fe74a.png)

2022-06-17 09:03 UTC, BenjaminSemah commented on src/components/AddCourseForm.js
> +  };
**RESOLVED** ✅ 
- Navigation has been included in the `handleFormSubmit` function.
- App now navigates to homepage after new course has been created.

2022-06-17 09:04 UTC, BenjaminSemah commented on src/pages/addCourse/AddCourse.css
> +}
**RESOLVED** ✅ 
- Background color has been removed from body.
- Background color now applies to only the `add-course` page.

2022-06-17 09:27 UTC, omarsalem7 approved these changes
Hi @BenjaminSemah 😊, 
# STATUS: APPROVED! 🥇 💯 

![giphy](https://media.giphy.com/media/n5VaQoW39Z9S0/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 🚀 
Congratulations! 🎉 

## Highlights
✅ No linter errors. 
✅ Descriptive pull request 
✅ Project has met all the technical aspects you needed for this project. Keep rocking! 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Code Review by @omarsalem7

2022-06-17 16:30 UTC, merged